name: format

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter: [black, isort, flake8, mypy]
        include:
          - linter: black
            command: black --check --diff .
          - linter: isort
            command: isort --check-only --diff .
          - linter: flake8
            command: flake8 --count .
          - linter: mypy
            command: mypy .
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install dependencies
        run: uv sync --frozen
      - name: Run ${{ matrix.linter }} check
        run: uv run ${{ matrix.command }}
